### ISSUE TITLE
可以在mac上跑吗

### ISSUE THREAD

**Issue by mkbk-with-circle** [zhuozhiyongde/PKU-Auto-Reservation#1]
你好，感谢您做出的项目成果，我想请问这个项目可以在mac的OS上跑吗，我跑了一下但是一直出现“[Failed]       : 暂不允许预约访客”

**Comment by zhuozhiyongde** [comment]
啊？我就是 macOS 上写的啊，你是不是配置文件填错了？

**Comment by mkbk-with-circle** [comment]
欸奇怪了，那我再试试哈！

**Comment by mkbk-with-circle** [comment]
我想问一下，您项目的思路就是，通过在iOS上获取验证码并且发送给PC端然后在电脑上完成预约过程对吧？

**Comment by mkbk-with-circle** [comment]
似乎还是不行，我认为我的yaml应该没有问题，哪怕是预约人信息错误应该也不只是“ 暂不允许预约访客”

**Comment by zhuozhiyongde** [comment]
有没有可能是门填错了，你用新燕园试一下

**Comment by zhuozhiyongde** [comment]
> 我想问一下，您项目的思路就是，通过在iOS上获取验证码并且发送给PC端然后在电脑上完成预约过程对吧？

是的

**Comment by mkbk-with-circle** [comment]
好滴
感谢建议！

**Comment by mkbk-with-circle** [comment]
欸现在可以了，现在是新燕园东门！但是按理说燕园东门应该没问题啊哈哈哈哈()

**Comment by mkbk-with-circle** [comment]
欸但是我虽然解绑了手机令牌，但是验证码是发送到微信上而不是通过短信发送？

**Comment by zhuozhiyongde** [comment]
> 欸但是我虽然解绑了手机令牌，但是验证码是发送到微信上而不是通过短信发送？

阿哲，这确实是不清楚的情况...

**Comment by mkbk-with-circle** [comment]
好趴，感谢大哥！

**Comment by mkbk-with-circle** [comment]
我尝试询问了一下chatgpt，看来在个人微信号上想要通过微信API获取验证码消息并且传输给python进程不太可行（或许解绑微信什么的就可以了），anyway依然感谢！
